Add PNG exporting feature using cairo
tuhiproject/tuhi pull request #221
Opened 2019-09-22 14:09 UTC by mont5piques

cairo is already installed (pygobject3); so no additionnal dependecy is required

2019-09-22 23:54 UTC, whot requested changes
Looks good, thanks. A few minor nitpicks, the only bigger thing I'd like us to think about is how we can share the code between the svg and the png converter - duplicating that will just lead to errors in the longer run.

2019-09-22 23:54 UTC, whot commented on tools/raw-log-converter.py
> +#!/usr/bin/env python3
can you send this as separate patch please, this one is just a bug that needs to be fixed anyway.

2019-09-22 23:54 UTC, whot commented on tuhi/gui/drawing.py
> +        self.process_png()  # sets self.png
I don't think this one is needed. we don't use the png in the GUI directly, so we can really just generate those on-demand before export.

2019-09-22 23:54 UTC, whot commented on tuhi/gui/drawing.py
> +        self.process_png()
same here

2019-09-22 23:54 UTC, whot commented on tuhi/gui/drawing.py
> +        # Translators: filter to show svg files only
this would need updating

2019-09-22 23:54 UTC, whot commented on tuhi/gui/drawing.py
> +                shutil.copyfile(self.png.filename, file)
I'd argue that after copying the file we should delete it from our own data path. we use svg primarily in the GUI and that's why we keep those around, but png is a purely export feature so we can delete it after saving it.

2019-09-22 23:54 UTC, whot commented on tuhi/gui/drawing.py
> +PNG_DATA_PATH = Path(xdg.BaseDirectory.xdg_cache_home, 'tuhi', 'png')
rename `DATA_PATH` to `SVG_DATA_PATH` for consistency please (could be done in a separate commit before this one).

2019-09-22 23:54 UTC, whot commented on tools/kete.py
> +    from tuhi.png import JsonPng
honestly, I wouldn't mind just shoving the png bits into `tuhi.svg`. Or possibly renaming it to `tuhi.image` or something.

2019-09-22 23:54 UTC, whot commented on tuhi/png.py
> +            # Original dimensions are too big for SVG Standard
SVG? :)

2019-09-22 23:54 UTC, whot commented on tuhi/png.py
> +            size = (width, height )
space before ` )`. btw, run `flake-8` and that should complain about this. Or install `flake-8` and run `ninja test` and that does the same.

2019-09-22 23:54 UTC, whot commented on tuhi/png.py
> +        surface.write_to_png(self.filename)
I can't think of a much better way right now (other than callbacks and whatnot) but it very much seems that we *should* be sharing the code with the `JsonSvg`. This is 90% the same and will eventually become the source of minor discrepancies as we forget to fix.

Maybe a parent class for the converter that calls the interface to add points/strokes which is then handled in the filetype-specific subclass?

2019-09-23 06:01 UTC, mont5piques commented on tuhi/png.py
> +            # Original dimensions are too big for SVG Standard
Copy paste for sure

2019-09-29 19:45 UTC, closed without merging

2019-09-29 23:47 UTC, whot commented
fwiw, you can just force-push to a branch and then ping the maintainer in the existing PR, no need to file a new PR for every iteration of the patch.

2019-09-29 23:47 UTC, whot commented
oh, and the explicit ping is necessary because github doesn't (didn't) always notify for force-pushes. In this case I got the email though so the ping is more a "it's ready now" notification.