Workaround for Spark register problems
tuhiproject/tuhi pull request #234
Opened 2020-01-02 20:06 UTC by niclashoyer

This is a workaround for #229. I got the same issues described in #229 and noticed while debugging, that the `GENERAL_ERROR` occurs, which should have been raised as an `AuthorizeException`, but it instead reaches the handler as `DeviceError`. I don't know where this originates, but using this workaround worked for me.

2020-01-03 00:53 UTC, whot requested changes
Same as with the other PR, please make sure the detailed explanation is in the commit message, thanks.

2020-01-03 11:05 UTC, niclashoyer commented
@whot I changed the commit message

2020-01-07 00:59 UTC, whot approved these changes

2020-01-07 01:00 UTC, merged

2020-01-07 01:00 UTC, whot commented
thanks!