Create it.po
tuhiproject/tuhi pull request #263
Opened 2020-09-02 18:53 UTC by albanobattistella

2020-09-02 22:22 UTC, whot requested changes
Just a few nitpicks, please squash the two commits together as well, thanks.

2020-09-02 22:22 UTC, whot commented on po/LINGUAS
> +it
hehe, did you see the comment above? :smile:

2020-09-02 22:22 UTC, whot commented on po/it.po
> +# Polish translation for tuhi.
I admit my polish is at zero but my italian is slightly above zero, so I can say with some confidence that this file is not a polish translation :)

2020-09-02 22:22 UTC, whot commented on po/it.po
> +msgstr "tablet;wacom;ink;"
shouldn't the search terms be translated too? or would you actually search for "ink" as opposed to "inchiostro" [1]


[1] google translate

2020-09-02 22:22 UTC, whot commented on po/it.po
> +msgstr "pagina0"
FTR, I filed #264 for this

2020-09-03 23:43 UTC, whot commented on po/it.po
> +msgstr "pagina0"
#264 is merged now, if you rebase on top of master the various `page0` ones should go away.

2020-09-07 02:11 UTC, whot commented
ftr, I can see the pushes you do but please ping me when you're ready for a review again so I don't waste time on an intermediate solution. Any comment you addressed please click the "Resolve conversation" button where there is nothing more to add, thanks.

2020-09-07 19:19 UTC, albanobattistella commented
> ftr, I can see the pushes you do but please ping me when you're ready for a review again so I don't waste time on an intermediate solution. Any comment you addressed please click the "Resolve conversation" button where there is nothing more to add, thanks.

Hi, 
no other to add.

2020-09-07 22:22 UTC, whot requested changes
minor issue that I can spot here, let me know if that comment is bogus though

2020-09-07 22:22 UTC, whot commented on po/it.po
> +Tuhi richiede Tuhi, il demone per comunicare effettivamente con i dispositivi."
i think there's a quote missing here

2020-09-08 12:43 UTC, albanobattistella commented on po/it.po
> +Tuhi richiede Tuhi, il demone per comunicare effettivamente con i dispositivi."
> i think there's a quote missing here

solved.

2020-09-08 21:13 UTC, whot approved these changes

2020-09-08 21:14 UTC, merged

2020-09-08 21:14 UTC, whot commented
Thanks, merged